package com.burton.finance.domain

object MarketCatalog {
    val groups: List<MarketGroup> = listOf(
        group(
            "US indices",
            "United States",
            MarketBoard.US,
            AssetKind.Index,
            listOf(
                "^GSPC" to "S&P 500",
                "^DJI" to "Dow Jones",
                "^IXIC" to "Nasdaq Composite",
                "^RUT" to "Russell 2000",
                "^VIX" to "CBOE VIX",
            ),
        ),
        group(
            "US large caps",
            "United States",
            MarketBoard.US,
            AssetKind.Equity,
            listOf(
                "AAPL" to "Apple",
                "MSFT" to "Microsoft",
                "NVDA" to "NVIDIA",
                "GOOGL" to "Alphabet",
                "AMZN" to "Amazon",
                "META" to "Meta",
                "BRK-B" to "Berkshire Hathaway",
                "LLY" to "Eli Lilly",
                "AVGO" to "Broadcom",
                "JPM" to "JPMorgan Chase",
                "TSLA" to "Tesla",
                "UNH" to "UnitedHealth",
                "XOM" to "Exxon Mobil",
                "V" to "Visa",
                "MA" to "Mastercard",
                "JNJ" to "Johnson & Johnson",
                "WMT" to "Walmart",
                "PG" to "Procter & Gamble",
                "HD" to "Home Depot",
                "COST" to "Costco",
                "ORCL" to "Oracle",
                "NFLX" to "Netflix",
                "KO" to "Coca-Cola",
                "PEP" to "PepsiCo",
                "BAC" to "Bank of America",
                "ABBV" to "AbbVie",
                "CRM" to "Salesforce",
                "AMD" to "AMD",
                "CSCO" to "Cisco",
                "DIS" to "Disney",
                "ADBE" to "Adobe",
                "INTC" to "Intel",
                "QCOM" to "Qualcomm",
                "IBM" to "IBM",
                "GE" to "GE Aerospace",
                "CAT" to "Caterpillar",
                "GS" to "Goldman Sachs",
                "AXP" to "American Express",
                "NKE" to "Nike",
                "BA" to "Boeing",
            ),
        ),
        group(
            "US ETFs",
            "United States",
            MarketBoard.US,
            AssetKind.Etf,
            listOf(
                "SPY" to "SPDR S&P 500",
                "QQQ" to "Invesco QQQ",
                "IWM" to "iShares Russell 2000",
                "VTI" to "Vanguard Total Stock",
                "VOO" to "Vanguard S&P 500",
                "GLD" to "SPDR Gold",
                "TLT" to "iShares 20+ Year Treasury",
            ),
        ),
        group(
            "United Kingdom",
            "United Kingdom",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^FTSE" to "FTSE 100",
                "SHEL.L" to "Shell",
                "AZN.L" to "AstraZeneca",
                "HSBA.L" to "HSBC",
                "ULVR.L" to "Unilever",
                "BP.L" to "BP",
                "GSK.L" to "GSK",
                "RIO.L" to "Rio Tinto",
                "DGE.L" to "Diageo",
                "BATS.L" to "British American Tobacco",
                "VOD.L" to "Vodafone",
                "LLOY.L" to "Lloyds",
                "BARC.L" to "Barclays",
            ),
            kinds = mapOf("^FTSE" to AssetKind.Index),
        ),
        group(
            "Japan",
            "Japan",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^N225" to "Nikkei 225",
                "7203.T" to "Toyota",
                "6758.T" to "Sony",
                "9984.T" to "SoftBank",
                "6861.T" to "Keyence",
                "8306.T" to "Mitsubishi UFJ",
                "4063.T" to "Shin-Etsu",
                "6098.T" to "Recruit",
                "9432.T" to "NTT",
                "8035.T" to "Tokyo Electron",
                "6501.T" to "Hitachi",
            ),
            kinds = mapOf("^N225" to AssetKind.Index),
        ),
        group(
            "Hong Kong",
            "Hong Kong",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^HSI" to "Hang Seng",
                "0700.HK" to "Tencent",
                "9988.HK" to "Alibaba",
                "3690.HK" to "Meituan",
                "0941.HK" to "China Mobile",
                "0005.HK" to "HSBC Holdings",
                "1299.HK" to "AIA",
                "0388.HK" to "HKEX",
                "1810.HK" to "Xiaomi",
                "9618.HK" to "JD.com",
            ),
            kinds = mapOf("^HSI" to AssetKind.Index),
        ),
        group(
            "Europe",
            "Europe",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^GDAXI" to "DAX",
                "^FCHI" to "CAC 40",
                "SAP.DE" to "SAP",
                "SIE.DE" to "Siemens",
                "ALV.DE" to "Allianz",
                "MC.PA" to "LVMH",
                "OR.PA" to "L'Oréal",
                "TTE.PA" to "TotalEnergies",
                "AIR.PA" to "Airbus",
                "ASML.AS" to "ASML",
                "NESN.SW" to "Nestlé",
                "ROG.SW" to "Roche",
                "NOVN.SW" to "Novartis",
                "UCG.MI" to "UniCredit",
                "ITX.MC" to "Inditex",
            ),
            kinds = mapOf("^GDAXI" to AssetKind.Index, "^FCHI" to AssetKind.Index),
        ),
        group(
            "Canada",
            "Canada",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^GSPTSE" to "S&P/TSX Composite",
                "RY.TO" to "Royal Bank of Canada",
                "TD.TO" to "TD Bank",
                "SHOP.TO" to "Shopify",
                "CNR.TO" to "Canadian National Railway",
                "ENB.TO" to "Enbridge",
                "BMO.TO" to "BMO",
            ),
            kinds = mapOf("^GSPTSE" to AssetKind.Index),
        ),
        group(
            "Australia",
            "Australia",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^AXJO" to "S&P/ASX 200",
                "BHP.AX" to "BHP",
                "CBA.AX" to "Commonwealth Bank",
                "CSL.AX" to "CSL",
                "NAB.AX" to "NAB",
                "WBC.AX" to "Westpac",
                "WES.AX" to "Wesfarmers",
            ),
            kinds = mapOf("^AXJO" to AssetKind.Index),
        ),
        group(
            "India",
            "India",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^NSEI" to "Nifty 50",
                "RELIANCE.NS" to "Reliance Industries",
                "TCS.NS" to "Tata Consultancy",
                "HDFCBANK.NS" to "HDFC Bank",
                "INFY.NS" to "Infosys",
                "ICICIBANK.NS" to "ICICI Bank",
                "BHARTIARTL.NS" to "Bharti Airtel",
            ),
            kinds = mapOf("^NSEI" to AssetKind.Index),
        ),
        group(
            "Korea",
            "Korea",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^KS11" to "KOSPI",
                "005930.KS" to "Samsung Electronics",
                "000660.KS" to "SK Hynix",
                "035420.KS" to "Naver",
                "005380.KS" to "Hyundai Motor",
                "051910.KS" to "LG Chem",
            ),
            kinds = mapOf("^KS11" to AssetKind.Index),
        ),
        group(
            "Greater China",
            "China",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "601318.SS" to "Ping An",
                "600519.SS" to "Kweichow Moutai",
                "601988.SS" to "Bank of China",
                "000333.SZ" to "Midea",
                "2330.TW" to "TSMC",
                "2317.TW" to "Hon Hai",
            ),
        ),
        group(
            "Brazil",
            "Brazil",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "^BVSP" to "Bovespa",
                "PETR4.SA" to "Petrobras",
                "VALE3.SA" to "Vale",
                "ITUB4.SA" to "Itaú Unibanco",
            ),
            kinds = mapOf("^BVSP" to AssetKind.Index),
        ),
        group(
            "Singapore",
            "Singapore",
            MarketBoard.International,
            AssetKind.Equity,
            listOf(
                "D05.SI" to "DBS",
                "O39.SI" to "OCBC",
                "U11.SI" to "UOB",
            ),
        ),
    )

    val listings: List<CatalogListing> = groups.flatMap { it.listings }

    val byId: Map<String, CatalogListing> = listings.associateBy { it.id }

    val yahooSymbols: List<String> = listings.map { it.symbol }.distinct()

    fun listing(symbol: String): CatalogListing? = byId[symbol]

    fun groupsFor(board: MarketBoard): List<MarketGroup> = groups.filter { it.board == board }

    private fun group(
        title: String,
        region: String,
        board: MarketBoard,
        kind: AssetKind,
        rows: List<Pair<String, String>>,
        kinds: Map<String, AssetKind> = emptyMap(),
    ): MarketGroup = MarketGroup(
        title = title,
        region = region,
        board = board,
        listings = rows.map { (symbol, name) ->
            CatalogListing(
                id = symbol,
                symbol = symbol,
                name = name,
                exchange = region,
                region = region,
                kind = kinds[symbol] ?: if (symbol.startsWith("^")) AssetKind.Index else kind,
            )
        },
    )
}
